os: osx
osx_image: xcode10.2

language: bash


install:
  - whoami
  - echo "Start of pipeline"
  - HOMWBREW_NO_AUTO_UPDATE=1

script:
  - ls
  - chmod +x hello.sh
  - ./hello.sh

after_script:
  - echo "End of pipline"

